language: python

python:
  - "2.7"

before_install:
  - rm setup.py
  - mv setup.py.travis setup.py
  - rm requirements.txt
  - mv requirements.txt.travis requirements.txt

install:
  - python setup.py install
  - pip install -r requirements.txt

  - which python
  - which pip
  - py.test --version

script:
  - py.test -v tests
