os: osx

language: python

python:
  - "2.7"

install:
  - python setup.py install
  - pip install -r requirements.txt

  - which python
  - which pip
  - py.test --version

script:
  - py.test -v tests
